name: Service
description: Creates new task revision and update ECR service 
inputs:
  aws-region:
    description: AWS region
    required: true
    default: 'eu-west-1'
  environment:
    description: Target CDK environment
    required: true
  role:
    description: Assume role
    required: true
  service-name:
    description: Service name
    required: true
    default: admin
  repository:
    description: ECR respository name
    required: true
    default: techloop/admin
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role }}
        #role-session-name: MySessionName # Optional
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Download task definition
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        SERVICE_NAME: ${{ inputs.service }}
      run: |
        aws ecs describe-task-definition --task-definition $SERVICE_NAME-$ENVIRONMENT-definition --query taskDefinition > task-definition.json
    - name: Fill in the new image ID
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ inputs.service }}-container
        image: ${{ steps.login-ecr.outputs.registry }}/${{ env.REPOSITORY }}:${{ github.sha }}
    - name: Deploy new task revision
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ inputs.service }}
        cluster: ${{ inputs.environment }}-services
        wait-for-service-stability: false
